import Link from "next/link";
import Navbar from "@/components/Navbar";
import { IconGavel, IconSpark, IconDoc, IconUser } from "@/components/icons";
import Footer from "@/components/Footer";

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-base">
      <Navbar />

      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 py-16 text-center sm:py-24">
        <span className="chip mx-auto mb-6 inline-flex">
          <IconSpark width={13} height={13} className="text-accent" />
          About PeerReviewer
        </span>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
          AI-powered peer review,{" "}
          <span className="text-accent">built for researchers</span>
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-text-secondary">
          PeerReviewer helps researchers anticipate reviewer concerns before
          journal submission — giving you realistic, actionable feedback
          calibrated to your target venue.
        </p>
      </section>

      {/* Mission */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="card p-8">
          <h2 className="mb-4 text-2xl font-bold">Our Mission</h2>
          <p className="leading-relaxed text-text-secondary">
            Peer review is slow, opaque, and often discouraging — especially
            for early-career researchers. We built PeerReviewer to give every
            researcher access to fast, honest, pre-submission feedback. Not to
            replace journals, but to help you submit stronger work with more
            confidence.
          </p>
          <p className="mt-4 leading-relaxed text-text-secondary">
            Each reviewer is powered by a different AI model, so the panel
            reasons from genuinely independent vantage points rather than one
            model wearing multiple hats. A handling editor then synthesises the
            reviews against your target journal quartile bar.
          </p>
        </div>
      </section>

      {/* How it works deep */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <h2 className="mb-6 text-2xl font-bold">How It Works</h2>
        <div className="grid gap-4 sm:grid-cols-3">
          {[
            {
              icon: <IconDoc width={20} height={20} />,
              title: "Your manuscript stays private",
              desc: "PDFs are extracted in your browser — the file never leaves your device. Only the text is sent for review.",
            },
            {
              icon: <IconUser width={20} height={20} />,
              title: "Multiple independent reviewers",
              desc: "Four reviewer personas each focus on a different dimension: methodology, novelty, validity, and clarity.",
            },
            {
              icon: <IconGavel width={20} height={20} />,
              title: "Calibrated to your target venue",
              desc: "Q1 to Q4 calibration means the same paper is judged against the right bar — not one-size-fits-all.",
            },
          ].map((item, i) => (
            <div key={i} className="card p-5">
              <span className="grid h-10 w-10 place-items-center rounded-md bg-accent/15 text-accent">
                {item.icon}
              </span>
              <h3 className="mt-3 font-semibold">{item.title}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-text-secondary">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Disclaimer */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="rounded-xl border border-amber-400/20 bg-amber-500/5 p-6">
          <h2 className="mb-3 font-semibold text-amber-300">Important Disclaimer</h2>
          <p className="text-sm leading-relaxed text-text-secondary">
            Reviews generated by PeerReviewer are AI-generated for guidance
            and rehearsal purposes only. They are designed to help authors
            anticipate reviewer concerns before submission — they do{" "}
            <strong className="text-text-primary">not</strong> replace a
            journal&apos;s formal peer review process. Decisions made by
            PeerReviewer carry no academic weight and should not be cited or
            used as evidence of peer review.
          </p>
        </div>
      </section>

      {/* Built by */}
      <section className="mx-auto max-w-4xl px-6 pb-16">
        <div className="card p-8 text-center">
          <h2 className="mb-2 text-xl font-bold">Built by Albatross Technologies</h2>
          <p className="mx-auto max-w-lg text-sm leading-relaxed text-text-secondary">
            Albatross Technologies builds AI-powered tools for researchers and
            academics. PeerReviewer is powered by NVIDIA NIM — an
            OpenAI-compatible inference platform running state-of-the-art
            language models.
          </p>
          <div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row">
            <Link href="/register" className="btn-primary !px-6 !py-2.5 text-sm">
              Get Started Free
            </Link>
            <a
              href="https://build.nvidia.com"
              target="_blank"
              rel="noreferrer"
              className="btn-outline !px-6 !py-2.5 text-sm"
            >
              NVIDIA NIM
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}